name: container action

on: push


jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    container: node:14.16
    services:
      nginx:
        image: nginx:latest
        ports: 
          - 8080:80
    steps: 
      - name: check node version
        run: node -v
      - name: test server
        uses: wei/curl@master
        with: 
          args: localhost:8080
