name: create artifactory

on: push

env:
  ARTIFACTORY_NAME: python_artifact
  
jobs:
  create_artifact:
    runs-on: ubuntu-latest
    steps: 
      - name: check out code
        uses: actions/checkout@v2
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with: 
          name: ${{ env.ARTIFACTORY_NAME }}
          path: .
          
        
