name: multiple jobs

on: push


jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps: 
      - name: check system info
        run: systeminfo
  windows-job:
    runs-on: windows-latest
    steps: 
      - name: check system info
        run: cat /etc/os-release
  macos-job:
    runs-on: macos-latest
    steps: 
      - name: check system info
        run: sw_vers
